---
title: "Lauren Whightsil"
---
*****
# Experience

#### GIS Intern, UC Santa Barbara Environmental Health and Safety: Emergency Management and Mission Continuity

  **April 2021 - present**

  - Created GIS maps in ArcGIS Pro to assist in Emergency Management.
  - Created a map of geocoded facilities for the University of California's Natural Reserve System, for researcher use and wildfire management of essential structures.
  
#### Volunteer, The Research Experience and Education Facility

  **August 2019 - June 2020**

  - Practiced aquarium husbandry and educated visitors on the local marine ecosystems.
  
#### Summer Office Intern, UCSB Grounds Department

  **August 2019 - September 2019**

  - Created an employee filing system and operated TreeKeeper to increase office efficiency.

#### Student Groundskeeper, Manzanita Restoration Site

  **February 2019 - June 2019**

  - Identified and removed invasive plants to maintain the grounds at the campus restoration site.

# Education

#### University of California, Santa Barbara

  **August 2018 - present**

#### Etiwanda High School, Rancho Cucamonga

  **August 2014 - May 2018**
  
  - GPA: 4.3 weighted

# Extracurriculars

#### GauchoCatholic

  - Club Secretary **August 2020 - present**
  
  - Events Co-chair **August 2019 - June 2020**

#### Alpha Sigma Kappa, Women in Technical Studies
  - member **April 2019 - present**
